version: '3'

services:

  # registry 
  istry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - istry:/var/lib/registry
    restart: "always"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.registry == true

volumes:
  istry:
